/**
 * CIGARCONNECT — Base de Données Initiale & Données de Démonstration
 * "Un lieu à la hauteur de votre collection." — Where Cigars Connect
 * 
 * NOTE DE CONFORMITÉ (Cahier des charges V1.0 - Section 1) :
 * Ce fichier contient exclusivement des données de démonstration pour le prototype.
 * Aucune certification, partenariat commercial ou garantie n'est affirmé sans protocole réel.
 */

const IS_DEMO_ENVIRONMENT = true;

const DEMO_CATALOG_CIGARS = [
  {
    id: "cig-behike-56",
    brand: "Cohiba",
    name: "Behike BHK 56",
    origin: "Cuba",
    countryCode: "CU",
    vitola: "Laguito No. 6",
    ringGauge: 56,
    lengthMm: 166,
    vintage: "2010",
    harvestYear: "Récolte 2007",
    boxYear: "Mise en boîte : Mai 2010",
    acquisitionDate: "Acquis en 2018 (Vente aux enchères de collection)",
    provenance: "Manufacture El Laguito, La Havane. Bague et marquage usine vérifiés par le propriétaire.",
    declaredConservation: "Armoire en cèdre espagnol régulée électroniquement à 18.5°C et 69% HR",
    conservationHr: "69% HR",
    boxCode: "BBM MAY 10",
    isBoxCodeDocumented: true,
    verificationStatus: "Déclaré par le membre (documents d'origine fournis)",
    rarity: "ultra-rare",
    rarityLabel: "Édition Limitée Historique",
    strength: 5,
    valuation: {
      amount: 450,
      currency: "EUR",
      source: "Estimation déclarée par le propriétaire (Cote indicative du marché)",
      isPrivate: false
    },
    owner: "Alexandre V.",
    ownerAvatar: "AV",
    ownerLocation: "Île-de-France, France",
    ownerBadge: "Membre du Cercle",
    ownerReputation: "Profil vérifié",
    image: "assets/cigar-behike56.jpg",
    gallery: [
      "assets/cigar-behike56.jpg",
      "assets/hero-cigar-library.jpg"
    ],
    aromas: ["Cuir Noble", "Cèdre de Cuba", "Cacao Noir", "Sous-Bois", "Terre Fertile"],
    description: "Le sommet de la manufacture El Laguito. Intègre la rare feuille de 'Medio Tiempo' cueillie sur les deux étages foliaires supérieurs des plants de tabac de la Vuelta Abajo.",
    status: "Disponible pour échange"
  },
  {
    id: "cig-trinidad-fundadores",
    brand: "Trinidad",
    name: "Fundadores Vintage Cabinet 1998",
    origin: "Cuba",
    countryCode: "CU",
    vitola: "Laguito Especial",
    ringGauge: 40,
    lengthMm: 192,
    vintage: "1998",
    harvestYear: "Récolte 1996",
    boxYear: "Mise en boîte : Juillet 1998",
    acquisitionDate: "Acquis en 2015 (Collection privée, Suisse)",
    provenance: "Boîte cabinet 24 pièces, issue des allocations diplomatiques historiques.",
    declaredConservation: "Humidor en cèdre massif, régulation 68% HR Boveda",
    conservationHr: "68% HR",
    boxCode: "EOG 07 98",
    isBoxCodeDocumented: true,
    verificationStatus: "Déclaré par le membre (bague et scellé photographiés)",
    rarity: "vintage",
    rarityLabel: "Cabinet Millésimé",
    strength: 3,
    valuation: {
      amount: 390,
      currency: "EUR",
      source: "Estimation déclarée par le propriétaire",
      isPrivate: false
    },
    owner: "Henri de B.",
    ownerAvatar: "HB",
    ownerLocation: "Canton de Zurich, Suisse",
    ownerBadge: "Collectionneur",
    ownerReputation: "Profil vérifié",
    image: "assets/cigar-fundadores.jpg",
    gallery: [
      "assets/cigar-fundadores.jpg",
      "assets/hero-cigar-library.jpg"
    ],
    aromas: ["Noisette Fraîche", "Cèdre Délicat", "Fève Tonka", "Miel d'Acacia"],
    description: "Vitole emblématique dotée de la coiffe en queue de cochon ('pig-tail') caractéristique de la manufacture de Pinar del Río.",
    status: "Disponible pour échange"
  },
  {
    id: "cig-montecristo-2-reserva",
    brand: "Montecristo",
    name: "No. 2 Reserva Cosecha 2002",
    origin: "Cuba",
    countryCode: "CU",
    vitola: "Pirámide",
    ringGauge: 52,
    lengthMm: 156,
    vintage: "2006",
    harvestYear: "Récolte Cosecha 2002",
    boxYear: "Mise en boîte : Novembre 2006",
    acquisitionDate: "Acquis en 2019 (Boutique officielle, Bâle)",
    provenance: "Série numérotée tirée à 5 000 coffrets laqués noirs. Tabacs vieillis 3 ans avant roulage.",
    declaredConservation: "Armoire de conservation tempérée 19°C / 69% HR constante",
    conservationHr: "69% HR",
    boxCode: "LUB NOV 06",
    isBoxCodeDocumented: true,
    verificationStatus: "Déclaré par le membre",
    rarity: "exclusive",
    rarityLabel: "Reserva Numérotée",
    strength: 4,
    valuation: {
      amount: 320,
      currency: "EUR",
      source: "Estimation déclarée par le propriétaire",
      isPrivate: false
    },
    owner: "Marc-Antoine G.",
    ownerAvatar: "MG",
    ownerLocation: "Genève, Suisse",
    ownerBadge: "Membre du Cercle",
    ownerReputation: "Profil vérifié",
    image: "assets/cigar-montecristo2.jpg",
    gallery: [
      "assets/cigar-montecristo2.jpg",
      "assets/hero-cigar-library.jpg"
    ],
    aromas: ["Espresso Ristretto", "Chocolat Amer", "Terre Noire", "Noix Grillées"],
    description: "Format piramide classique roulé avec des feuilles sélectionnées de la récolte 2002 de la région de Vuelta Abajo.",
    status: "Disponible pour échange"
  },
  {
    id: "cig-partagas-lusitanias-gr",
    brand: "Partagás",
    name: "Lusitanias Gran Reserva Cosecha 2007",
    origin: "Cuba",
    countryCode: "CU",
    vitola: "Prominente (Double Corona)",
    ringGauge: 49,
    lengthMm: 194,
    vintage: "2013",
    harvestYear: "Récolte Cosecha 2007",
    boxYear: "Mise en boîte : Décembre 2013",
    acquisitionDate: "Acquis en 2021 (Vente privée de collection)",
    provenance: "Coffret n° 1422 / 5000. Tabacs vieillis 5 ans en fûts de cèdre.",
    declaredConservation: "Cave de conservation régulée électroniquement à 69% HR et 18°C",
    conservationHr: "69% HR",
    boxCode: "MUP DIC 13",
    isBoxCodeDocumented: true,
    verificationStatus: "Déclaré par le membre (documents examinés)",
    rarity: "ultra-rare",
    rarityLabel: "Gran Reserva",
    strength: 5,
    valuation: {
      amount: 520,
      currency: "EUR",
      source: "Estimation déclarée par le propriétaire",
      isPrivate: false
    },
    owner: "Samuel L.",
    ownerAvatar: "SL",
    ownerLocation: "Bruxelles, Belgique",
    ownerBadge: "Collectionneur",
    ownerReputation: "Profil vérifié",
    image: "assets/cigar-lusitanias.jpg",
    gallery: [
      "assets/cigar-lusitanias.jpg",
      "assets/hero-cigar-library.jpg"
    ],
    aromas: ["Cuir Sauvage", "Terre Minérale", "Poivre Blanc", "Bois de Chêne"],
    description: "Double corona d'une grande plénitude, combinant l'intensité aromatique traditionnelle de Partagás et la rondeur du vieillissement.",
    status: "Disponible pour échange"
  },
  {
    id: "cig-davidoff-oroblanco",
    brand: "Davidoff",
    name: "Oro Blanco Special Reserve 2002",
    origin: "République Dominicaine",
    countryCode: "DO",
    vitola: "Toro Extra",
    ringGauge: 54,
    lengthMm: 152,
    vintage: "2002",
    harvestYear: "Récolte Exceptionnelle 2002",
    boxYear: "Mise en boîte : 2014 (Après 12 ans d'affinage)",
    acquisitionDate: "Acquis en 2020 (Flagship store officiel)",
    provenance: "Tabacs affinés pendant plus de 12 ans, signé individuellement par le Master Blender.",
    declaredConservation: "Humidor personnel marbre et cèdre, régulation 70% HR Boveda",
    conservationHr: "70% HR",
    boxCode: "ORO-BL-02-VIP",
    isBoxCodeDocumented: true,
    verificationStatus: "Déclaré par le membre",
    rarity: "ultra-rare",
    rarityLabel: "Trésor Royal",
    strength: 3,
    valuation: {
      amount: 620,
      currency: "EUR",
      source: "Facture d'achat d'origine déclarée",
      isPrivate: false
    },
    owner: "Alexandre de Montmirail (Vous)",
    ownerAvatar: "AM",
    ownerLocation: "Paris, France",
    ownerBadge: "Membre du Cercle",
    ownerReputation: "Profil vérifié",
    image: "assets/cigar-oroblanco.jpg",
    gallery: [
      "assets/cigar-oroblanco.jpg",
      "assets/hero-cigar-library.jpg"
    ],
    aromas: ["Cèdre Espagnol", "Caramel Beurre Salé", "Épices Douces", "Fleur Blanche"],
    description: "Assemblage de tabacs dominicains rares de la récolte 2002 affinés pendant plus d'une décennie.",
    status: "Pièce de contemplation (Non négociable)"
  },
  {
    id: "cig-kashimbo-noble-origins",
    brand: "Kashimbo",
    name: "Heritage Noble Origins (Silver Band)",
    origin: "Haïti (Maison d'Auteur) · Terroirs d'Exception",
    countryCode: "HT",
    vitola: "Toro (54 x 152mm)",
    ringGauge: 54,
    lengthMm: 152,
    vintage: "2021",
    harvestYear: "Édition Heritage 2021",
    boxYear: "Mise en boîte : Boîte de 20 scellée",
    acquisitionDate: "Acquis en 2024 (Manufacture Kashimbo)",
    provenance: "Maison Kashimbo (Haïti / Ayiti). Assemblage de terroirs : cape San Andrés maduro (Mexique), sous-cape et tripe 100% nicaraguayennes roulées main.",
    declaredConservation: "Armoire en cèdre espagnol régulée à 19°C et 69% HR",
    conservationHr: "69% HR",
    boxCode: "KSH-NO-21",
    isBoxCodeDocumented: true,
    verificationStatus: "Certifié manufacture",
    rarity: "exclusive",
    rarityLabel: "Bague Argentée · Boîte de 20",
    strength: 3,
    valuation: {
      amount: 350,
      currency: "EUR",
      source: "Tarif officiel manufacture (Boîte de 20)",
      isPrivate: false
    },
    owner: "Alexandre de Montmirail (Vous)",
    ownerAvatar: "AM",
    ownerLocation: "Paris, France",
    ownerBadge: "Membre du Cercle",
    ownerReputation: "Profil vérifié",
    image: "assets/cigar-kashimbo-noble-origins.jpg",
    gallery: [
      "assets/cigar-kashimbo-noble-origins.jpg",
      "assets/kashimbo-cigars-banner.jpg"
    ],
    aromas: ["Chocolat Noir", "Poivre Vif", "Cuir Rustique", "Noisettes Grillées", "Crème Veloutée"],
    description: "Maison d'auteur née sous l'étoile d'Ayiti (Haïti). La direction artistique haïtienne s'allie à une cape San Andrés maduro et des tabacs nicaraguayens roulés main en tripa larga. Symphonie de chocolat noir, poivre vif et texture crémeuse.",
    status: "Disponible pour échange"
  },
  {
    id: "cig-kashimbo-majestic",
    brand: "Kashimbo",
    name: "Heritage Majestic (Gold Band)",
    origin: "Haïti (Maison d'Auteur) · Multi-Terroirs",
    countryCode: "HT",
    vitola: "Gordo (60 x 152mm)",
    ringGauge: 60,
    lengthMm: 152,
    vintage: "2021",
    harvestYear: "Édition Heritage 2021",
    boxYear: "Mise en boîte : Boîte de 20 scellée",
    acquisitionDate: "Acquis en 2024 (Manufacture Kashimbo)",
    provenance: "Maison Kashimbo (Haïti / Ayiti). Cape San Andrés (Mexique), sous-cape indonésienne, tripe République Dominicaine et Nicaragua.",
    declaredConservation: "Armoire en cèdre régulée à 19°C et 69% HR",
    conservationHr: "69% HR",
    boxCode: "KSH-MJ-21",
    isBoxCodeDocumented: true,
    verificationStatus: "Certifié manufacture",
    rarity: "ultra-rare",
    rarityLabel: "Bague Dorée Impériale · Boîte de 20",
    strength: 3,
    valuation: {
      amount: 420,
      currency: "EUR",
      source: "Tarif officiel manufacture (Boîte de 20)",
      isPrivate: false
    },
    owner: "Alexandre de Montmirail (Vous)",
    ownerAvatar: "AM",
    ownerLocation: "Paris, France",
    ownerBadge: "Membre du Cercle",
    ownerReputation: "Profil vérifié",
    image: "assets/cigar-kashimbo-majestic.jpg",
    gallery: [
      "assets/cigar-kashimbo-majestic.jpg",
      "assets/kashimbo-cigars-banner.jpg"
    ],
    aromas: ["Cacao Intense", "Épices Douces", "Café Torréfié", "Cèdre", "Terre Noble"],
    description: "Portée par la vision et l'héritage d'Haïti (Ayiti — « Timeless Enjoyment »). Ce chef-d'œuvre au format Gordo (cepo 60) unit une cape San Andrés à une sous-cape indonésienne et des tripes dominicaines et nicaraguayennes.",
    status: "Pièce de contemplation (Garde privée)"
  },
  {
    id: "cig-kashimbo-year-of-the-horse-2026",
    brand: "Kashimbo",
    name: "Year of the Horse — Limited Edition 2026",
    origin: "Haïti (Maison d'Auteur) · Édition Limitée 2026",
    countryCode: "HT",
    vitola: "Toro 5x56 (56 x 127mm)",
    ringGauge: 56,
    lengthMm: 127,
    vintage: "2026",
    harvestYear: "Millésime 2026",
    boxYear: "Boîte de 10 signée par les propriétaires",
    acquisitionDate: "Acquis en 2026 (Manufacture Kashimbo)",
    provenance: "Maison Kashimbo (Haïti / Ayiti) — Coffret officiel numéroté de 10 pièces contresigné sur le couvercle par les propriétaires fondateurs.",
    declaredConservation: "Cave de vieillissement cèdre régulée à 19°C et 69% HR",
    conservationHr: "69% HR",
    boxCode: "KSH-YOTH-26",
    isBoxCodeDocumented: true,
    verificationStatus: "Certifié manufacture",
    rarity: "limited-edition",
    rarityLabel: "Édition Limitée 2026 · Boîte Signée de 10",
    strength: 4,
    valuation: {
      amount: 480,
      currency: "EUR",
      source: "Tarif officiel manufacture (Boîte de 10 signée)",
      isPrivate: false
    },
    owner: "Alexandre de Montmirail (Vous)",
    ownerAvatar: "AM",
    ownerLocation: "Paris, France",
    ownerBadge: "Membre du Cercle",
    ownerReputation: "Profil vérifié",
    image: "assets/cigar-kashimbo-year-of-the-horse-2026.jpg",
    gallery: [
      "assets/cigar-kashimbo-year-of-the-horse-2026.jpg",
      "assets/kashimbo-cigars-banner.jpg"
    ],
    aromas: ["Cèdre Noble", "Cuir", "Café Torréfié", "Cacao Noir", "Épices de Pâtisserie"],
    description: "Maison d'auteur fièrement enracinée en Haïti (Ayiti). Édition commémorative 'Year of the Horse 2026' célébrant la force et l'élégance du cheval. Module Toro 5x56 au cepo 56, affiné avec maestria et présenté en boîte de 10 pièces contresignée sur le couvercle par les propriétaires fondateurs. Profil corsé et racé (Medium-Full to Full) : cèdre, cuir noble, café torréfié, cacao noir intense et épices douces sur une finale persistante et soyeuse.",
    status: "Disponible pour échange"
  },
  {
    id: "cig-kashimbo-year-of-the-snake-2025",
    brand: "Kashimbo",
    name: "Year of the Snake — Limited Edition 2025",
    origin: "Haïti (Maison d'Auteur) · Édition Limitée 2025",
    countryCode: "HT",
    vitola: "Figurado 6x56 (56 x 152mm)",
    ringGauge: 56,
    lengthMm: 152,
    vintage: "2025",
    harvestYear: "Millésime 2025",
    boxYear: "Édition Limitée 2025 scellée",
    acquisitionDate: "Acquis en 2025 (Manufacture Kashimbo)",
    provenance: "Maison Kashimbo (Haïti / Ayiti) — Cape Habano sun-grown, sous-cape Habano, tripe multi-terroirs d'exception : Ometepe, Condega, Estelí (Nicaragua) et République Dominicaine.",
    declaredConservation: "Cave de vieillissement cèdre régulée à 19°C et 69% HR",
    conservationHr: "69% HR",
    boxCode: "KSH-YOTS-25",
    isBoxCodeDocumented: true,
    verificationStatus: "Certifié manufacture",
    rarity: "limited-edition",
    rarityLabel: "Édition Limitée 2025 · Figurado 6x56",
    strength: 4,
    valuation: {
      amount: 520,
      currency: "EUR",
      source: "Tarif officiel manufacture (Édition Limitée)",
      isPrivate: false
    },
    owner: "Alexandre de Montmirail (Vous)",
    ownerAvatar: "AM",
    ownerLocation: "Paris, France",
    ownerBadge: "Membre du Cercle",
    ownerReputation: "Profil vérifié",
    image: "assets/cigar-kashimbo-year-of-the-snake-2025.jpg",
    gallery: [
      "assets/cigar-kashimbo-year-of-the-snake-2025.jpg",
      "assets/cigar-kashimbo-year-of-the-snake-spec.jpg",
      "assets/cigar-kashimbo-year-of-the-snake-tasting.jpg",
      "assets/kashimbo-cigars-banner.jpg"
    ],
    aromas: ["Espresso Noir", "Noisettes Grillées", "Vanille Crémeuse", "Chêne Noble", "Douceur Caramélisée"],
    description: "Maison d'auteur fièrement enracinée en Haïti (Ayiti). Édition commémorative 'Year of the Snake 2025' dédiée aux connaisseurs les plus exigeants. Module d'exception Figurado 6x56 (double perfecto biseauté de 152 mm, cepo 56) habillé d'une cape Habano sun-grown sans défaut et d'une sous-cape Habano. Tripe multi-terroirs mariant la puissance volcanique d'Ometepe, Condega, Estelí et la rondeur dominicaine. Notes d'espresso noir, noisettes grillées, vanille crémeuse, boisé noble et finale poivrée raffinée.",
    status: "Disponible pour échange"
  }
];

// Données Humidor Démonstration de l'utilisateur (avec gestion stricte du stock et confidentialité par défaut)
const DEMO_USER_HUMIDOR = [
  {
    id: "my-cig-1",
    brand: "Davidoff",
    name: "Oro Blanco Special Reserve 2002",
    origin: "République Dominicaine",
    vitola: "Toro Extra (54 x 152mm)",
    vintage: "2002",
    harvestYear: "Récolte 2002",
    boxYear: "2014",
    boxCode: "ORO-BL-02-VIP",
    quantity: 2,           // Quantité totale détenue
    reservedQuantity: 0,   // Quantité réservée dans un échange actif
    isTradeable: false,    // Collection privée par défaut (Section 3.1)
    isPublic: false,       // Non visible publiquement par défaut
    conditionHr: "70% HR",
    conditionTemp: "19.2°C",
    valuation: {
      amount: 620,
      currency: "EUR",
      source: "Facture d'origine déclarée",
      isPrivate: true
    },
    dateAdded: "12/03/2024",
    image: "assets/cigar-oroblanco.jpg",
    provenance: "Boutique officielle, Genève",
    conservation: "Humidor Cèdre Privé (70% HR)"
  },
  {
    id: "my-cig-2",
    brand: "Cohiba",
    name: "Behike BHK 56",
    origin: "Cuba",
    vitola: "Laguito No. 6 (56 x 166mm)",
    vintage: "2010",
    harvestYear: "Récolte 2007",
    boxYear: "2010",
    boxCode: "BBM MAY 10",
    quantity: 3,
    reservedQuantity: 1,   // 1 unité actuellement engagée dans un échange
    isTradeable: true,
    isPublic: true,
    conditionHr: "69% HR",
    conditionTemp: "18.5°C",
    valuation: {
      amount: 450,
      currency: "EUR",
      source: "Estimation personnelle",
      isPrivate: true
    },
    dateAdded: "05/06/2024",
    image: "assets/cigar-behike56.jpg",
    provenance: "Acquisition aux enchères 2018",
    conservation: "Armoire Cèdre 69% HR"
  },
  {
    id: "my-cig-3",
    brand: "Trinidad",
    name: "Fundadores Vintage Cabinet 1998",
    origin: "Cuba",
    vitola: "Laguito Especial (40 x 192mm)",
    vintage: "1998",
    harvestYear: "Récolte 1996",
    boxYear: "1998",
    boxCode: "EOG 07 98",
    quantity: 2,
    reservedQuantity: 0,
    isTradeable: true,
    isPublic: true,
    conditionHr: "68% HR",
    conditionTemp: "19.0°C",
    valuation: {
      amount: 390,
      currency: "EUR",
      source: "Estimation personnelle",
      isPrivate: true
    },
    dateAdded: "18/08/2024",
    image: "assets/cigar-fundadores.jpg",
    provenance: "Collection privée Berne",
    conservation: "Humidor Cèdre 68% HR"
  },
  {
    id: "my-cig-4",
    brand: "Partagás",
    name: "Lusitanias Gran Reserva Cosecha 2007",
    origin: "Cuba",
    vitola: "Prominente (49 x 194mm)",
    vintage: "2013",
    harvestYear: "Récolte 2007",
    boxYear: "2013",
    boxCode: "MUP DIC 13",
    quantity: 1,
    reservedQuantity: 0,
    isTradeable: false,
    isPublic: false,
    conditionHr: "69% HR",
    conditionTemp: "18.2°C",
    valuation: {
      amount: 520,
      currency: "EUR",
      source: "Vente aux enchères 2021",
      isPrivate: true
    },
    dateAdded: "29/11/2024",
    image: "assets/cigar-lusitanias.jpg",
    provenance: "Vente aux enchères Londres",
    conservation: "Cave EuroCave 18°C / 69% HR"
  },
  {
    id: "my-cig-kashimbo-noble",
    brand: "Kashimbo",
    name: "Heritage Noble Origins (Silver Band)",
    origin: "Haïti (Maison d'Auteur) · Terroirs d'Exception",
    vitola: "Toro 6x54 (54 x 152mm)",
    vintage: "2021",
    harvestYear: "Récolte Heritage",
    boxYear: "2021",
    boxCode: "KSH-NO-21",
    quantity: 10,
    reservedQuantity: 0,
    isTradeable: true,
    isPublic: true,
    conditionHr: "69% HR",
    conditionTemp: "19.0°C",
    valuation: {
      amount: 350,
      currency: "EUR",
      source: "Acquisition directe manufacture",
      isPrivate: true
    },
    dateAdded: "15/09/2024",
    image: "assets/cigar-kashimbo-noble-origins.jpg",
    provenance: "Maison Kashimbo (Haïti / Ayiti) — Boîte verte officielle de 20 scellée en manufacture dédiée",
    conservation: "Armoire Cèdre Salon (69% HR Boveda)"
  },
  {
    id: "my-cig-kashimbo-majestic",
    brand: "Kashimbo",
    name: "Heritage Majestic (Gold Band)",
    origin: "Haïti (Maison d'Auteur) · Multi-Terroirs",
    vitola: "Gordo 6x60 (60 x 152mm)",
    vintage: "2021",
    harvestYear: "Récolte Heritage",
    boxYear: "2021",
    boxCode: "KSH-MJ-21",
    quantity: 5,
    reservedQuantity: 0,
    isTradeable: false,
    isPublic: true,
    conditionHr: "69% HR",
    conditionTemp: "19.0°C",
    valuation: {
      amount: 240,
      currency: "EUR",
      source: "Acquisition directe manufacture",
      isPrivate: true
    },
    dateAdded: "15/09/2024",
    image: "assets/cigar-kashimbo-majestic.jpg",
    provenance: "Maison Kashimbo (Haïti / Ayiti) — Boîte verte officielle de 20 scellée en manufacture dédiée",
    conservation: "Armoire Cèdre Salon (69% HR Boveda)"
  },
  {
    id: "my-cig-kashimbo-year-of-the-horse",
    brand: "Kashimbo",
    name: "Year of the Horse — Limited Edition 2026",
    origin: "Haïti (Maison d'Auteur) · Édition Limitée 2026",
    vitola: "Toro 5x56 (56 x 127mm)",
    vintage: "2026",
    harvestYear: "Millésime 2026",
    boxYear: "2026",
    boxCode: "KSH-YOTH-26",
    quantity: 10,
    reservedQuantity: 0,
    isTradeable: true,
    isPublic: true,
    conditionHr: "69% HR",
    conditionTemp: "19.0°C",
    valuation: {
      amount: 480,
      currency: "EUR",
      source: "Boîte officielle de 10 signée par les propriétaires",
      isPrivate: true
    },
    dateAdded: "25/09/2026",
    image: "assets/cigar-kashimbo-year-of-the-horse-2026.jpg",
    provenance: "Maison Kashimbo (Haïti / Ayiti) — Boîte officielle de 10 pièces numérotée et contresignée sur le dessus par les propriétaires fondateurs",
    conservation: "Armoire Cèdre Salon (69% HR Boveda)"
  },
  {
    id: "my-cig-kashimbo-year-of-the-snake",
    brand: "Kashimbo",
    name: "Year of the Snake — Limited Edition 2025",
    origin: "Haïti (Maison d'Auteur) · Édition Limitée 2025",
    vitola: "Figurado 6x56 (56 x 152mm)",
    vintage: "2025",
    harvestYear: "Millésime 2025",
    boxYear: "2025",
    boxCode: "KSH-YOTS-25",
    quantity: 5,
    reservedQuantity: 0,
    isTradeable: true,
    isPublic: true,
    conditionHr: "69% HR",
    conditionTemp: "19.0°C",
    valuation: {
      amount: 520,
      currency: "EUR",
      source: "Tarif officiel manufacture (Édition Limitée)",
      isPrivate: true
    },
    dateAdded: "25/09/2026",
    image: "assets/cigar-kashimbo-year-of-the-snake-2025.jpg",
    provenance: "Maison Kashimbo (Haïti / Ayiti) — Édition limitée officielle 2025 certifiée manufacture",
    conservation: "Armoire Cèdre Salon (69% HR Boveda)"
  }
];

// Propositions de Troc Structurées (Troc pur sans paiement en ligne - Section 3.1 & 8.1)
const DEMO_TRADES = [
  {
    id: "trade-001",
    version: 1,
    proposerName: "Alexandre V.",
    proposerReputation: "Profil vérifié",
    proposerLocation: "Île-de-France, France",
    offeredCigar: "Cohiba Behike BHK 56 (2010)",
    offeredQuantity: 1,
    desiredCigar: "Davidoff Oro Blanco (2002) ou Trinidad Fundadores 1998",
    desiredQuantity: 1,
    status: "Envoyée (En attente d'acceptation)",
    statusClass: "sent",
    notes: "Conservé en humidor cèdre régulé électroniquement à 69% HR. Bague holographique et marquage d'origine documentés.",
    date: "Il y a 3 heures",
    exchangeLocationType: "Remise physique en salon privé convenu d'un commun accord",
    exchangeMethod: "Troc direct entre membres majeurs",
    image: "assets/cigar-behike56.jpg"
  },
  {
    id: "trade-002",
    version: 2,
    proposerName: "Marc-Antoine G.",
    proposerReputation: "Profil vérifié",
    proposerLocation: "Genève, Suisse",
    offeredCigar: "Montecristo No. 2 Reserva Cosecha 2002",
    offeredQuantity: 1,
    desiredCigar: "Cohiba Behike BHK 56",
    desiredQuantity: 1,
    status: "Négociation en cours (Version 2)",
    statusClass: "negotiating",
    notes: "Échange envisageable en main propre à Genève ou expédition soignée sous sachet Boveda 69% en étui rigide hermétique.",
    date: "Hier à 18h40",
    exchangeLocationType: "Remise en main propre dans un lieu privé de dégustation",
    exchangeMethod: "Troc direct entre membres majeurs",
    image: "assets/cigar-montecristo2.jpg"
  },
  {
    id: "trade-003",
    version: 1,
    proposerName: "Samuel L.",
    proposerReputation: "Profil vérifié",
    proposerLocation: "Bruxelles, Belgique",
    offeredCigar: "Partagás Lusitanias Gran Reserva 2007",
    offeredQuantity: 1,
    desiredCigar: "Trinidad Fundadores 1998",
    desiredQuantity: 1,
    status: "Accord mutuel confirmé",
    statusClass: "agreed",
    notes: "Exemplaire sous observation. Roulé à partir des tabacs de la Cosecha 2007.",
    date: "Il y a 2 jours",
    exchangeLocationType: "Expédition protégée sous sachet Boveda 69% (Colis suivi)",
    exchangeMethod: "Troc direct entre membres majeurs",
    image: "assets/cigar-lusitanias.jpg"
  }
];

// Nouveautés partagées volontairement
const DEMO_NEW_ARRIVALS = [
  {
    id: "new-01",
    brand: "Trinidad",
    name: "Fundadores Edición 1998",
    origin: "Cuba",
    countryCode: "CU",
    vitola: "Laguito Especial",
    ringGauge: 40,
    lengthMm: 192,
    vintage: "1998",
    harvestYear: "Récolte 1996",
    declaredConservation: "Humidor cèdre (68% HR)",
    owner: "Henri de B.",
    ownerAvatar: "HB",
    ownerLocation: "Zurich, Suisse",
    ownerBadge: "Collectionneur",
    timeAgo: "Il y a 12 min",
    image: "assets/cigar-fundadores.jpg",
    isTradeable: true
  },
  {
    id: "new-02",
    brand: "Cohiba",
    name: "Behike BHK 56 (2010)",
    origin: "Cuba",
    countryCode: "CU",
    vitola: "Laguito No. 6",
    ringGauge: 56,
    lengthMm: 166,
    vintage: "2010",
    harvestYear: "Récolte 2007",
    declaredConservation: "Armoire tempérée (69% HR)",
    owner: "Alexandre V.",
    ownerAvatar: "AV",
    ownerLocation: "Paris, France",
    ownerBadge: "Membre du Cercle",
    timeAgo: "Il y a 45 min",
    image: "assets/cigar-behike56.jpg",
    isTradeable: true
  },
  {
    id: "new-03",
    brand: "Partagás",
    name: "Lusitanias Gran Reserva 2007",
    origin: "Cuba",
    countryCode: "CU",
    vitola: "Prominente",
    ringGauge: 49,
    lengthMm: 194,
    vintage: "2013",
    harvestYear: "Récolte 2007",
    declaredConservation: "Cave EuroCave (69% HR)",
    owner: "Samuel L.",
    ownerAvatar: "SL",
    ownerLocation: "Bruxelles, Belgique",
    ownerBadge: "Collectionneur",
    timeAgo: "Il y a 2h",
    image: "assets/cigar-lusitanias.jpg",
    isTradeable: true
  },
  {
    id: "new-04",
    brand: "Montecristo",
    name: "No. 2 Reserva Cosecha 2002",
    origin: "Cuba",
    countryCode: "CU",
    vitola: "Pirámide",
    ringGauge: 52,
    lengthMm: 156,
    vintage: "2006",
    harvestYear: "Récolte 2002",
    declaredConservation: "Armoire cèdre régulée (69% HR)",
    owner: "Marc-Antoine G.",
    ownerAvatar: "MG",
    ownerLocation: "Genève, Suisse",
    ownerBadge: "Membre du Cercle",
    timeAgo: "Il y a 3h",
    image: "assets/cigar-montecristo2.jpg",
    isTradeable: true
  }
];

// Rétrocompatibilité avec les variables d'origine pour fluidité
const INITIAL_CIGARS = DEMO_CATALOG_CIGARS;
const INITIAL_USER_HUMIDOR = DEMO_USER_HUMIDOR;
const INITIAL_TRADES = DEMO_TRADES;
const INITIAL_NEW_ARRIVALS = DEMO_NEW_ARRIVALS;
